--[[
	ItemDatabase.lua
	Master database of all items in The Purge: Suburban Survival
]]

local Enums = require(script.Parent.Enums)

local Cat = Enums.ItemCategory
local Tier = Enums.ItemTier

local ItemDatabase = {}

------------------------------------------------------------------------
-- Building Materials
------------------------------------------------------------------------
ItemDatabase.Items = {
	-- COMMON building materials
	plywood = {
		name = "Plywood",
		category = Cat.BuildingMaterial,
		tier = Tier.Common,
		description = "Thin plywood sheet. Won't hold long.",
		stackable = true,
		maxStack = 10,
		weight = 2,
	},
	duct_tape = {
		name = "Duct Tape",
		category = Cat.BuildingMaterial,
		tier = Tier.Common,
		description = "Fixes anything. Temporarily.",
		stackable = true,
		maxStack = 5,
		weight = 1,
	},
	wooden_planks = {
		name = "Wooden Planks",
		category = Cat.BuildingMaterial,
		tier = Tier.Common,
		description = "Basic lumber for boarding up entry points.",
		stackable = true,
		maxStack = 10,
		weight = 3,
	},
	nails = {
		name = "Nails",
		category = Cat.BuildingMaterial,
		tier = Tier.Common,
		description = "Box of nails. Essential for any barricade.",
		stackable = true,
		maxStack = 20,
		weight = 1,
	},
	scrap_metal = {
		name = "Scrap Metal",
		category = Cat.BuildingMaterial,
		tier = Tier.Common,
		description = "Bent metal scraps. Better than nothing.",
		stackable = true,
		maxStack = 8,
		weight = 3,
	},

	-- UNCOMMON building materials
	reinforced_boards = {
		name = "Reinforced Boards",
		category = Cat.BuildingMaterial,
		tier = Tier.Uncommon,
		description = "Thick hardwood boards with metal reinforcement.",
		stackable = true,
		maxStack = 8,
		weight = 4,
	},
	steel_nails = {
		name = "Steel Nails",
		category = Cat.BuildingMaterial,
		tier = Tier.Uncommon,
		description = "Heavy-duty steel nails that grip tight.",
		stackable = true,
		maxStack = 15,
		weight = 1,
	},
	chain_lock = {
		name = "Chain Lock",
		category = Cat.BuildingMaterial,
		tier = Tier.Uncommon,
		description = "Heavy chain and padlock for securing doors.",
		stackable = true,
		maxStack = 3,
		weight = 3,
	},
	sandbags = {
		name = "Sandbags",
		category = Cat.BuildingMaterial,
		tier = Tier.Uncommon,
		description = "Dense sandbags for building barricades.",
		stackable = true,
		maxStack = 6,
		weight = 5,
	},

	-- RARE building materials
	steel_panels = {
		name = "Steel Panels",
		category = Cat.BuildingMaterial,
		tier = Tier.Rare,
		description = "Industrial steel paneling. Extremely durable.",
		stackable = true,
		maxStack = 4,
		weight = 8,
	},
	bulletproof_glass = {
		name = "Bulletproof Glass",
		category = Cat.BuildingMaterial,
		tier = Tier.Rare,
		description = "Layered composite glass that stops bullets.",
		stackable = true,
		maxStack = 3,
		weight = 6,
	},
	industrial_lock = {
		name = "Industrial Lock",
		category = Cat.BuildingMaterial,
		tier = Tier.Rare,
		description = "Military-grade deadbolt system.",
		stackable = true,
		maxStack = 2,
		weight = 3,
	},
	steel_door = {
		name = "Steel Door",
		category = Cat.BuildingMaterial,
		tier = Tier.Rare,
		description = "Reinforced steel door. Nearly impenetrable.",
		stackable = false,
		maxStack = 1,
		weight = 12,
	},

	-- EPIC building / defense materials
	turret_components = {
		name = "Turret Components",
		category = Cat.Trap,
		tier = Tier.Epic,
		description = "Parts to assemble an automated turret.",
		stackable = false,
		maxStack = 1,
		weight = 10,
		requiresPower = true,
	},
	electric_fence_kit = {
		name = "Electric Fence Kit",
		category = Cat.Trap,
		tier = Tier.Epic,
		description = "Full electric fence perimeter kit.",
		stackable = false,
		maxStack = 1,
		weight = 8,
		requiresPower = true,
	},

	------------------------------------------------------------------------
	-- Traps
	------------------------------------------------------------------------
	spike_strip = {
		name = "Spike Strip",
		category = Cat.Trap,
		tier = Tier.Uncommon,
		description = "Concealed spikes that damage anyone who steps on them.",
		stackable = true,
		maxStack = 4,
		weight = 3,
		damage = 25,
	},
	tripwire = {
		name = "Tripwire Alarm",
		category = Cat.Trap,
		tier = Tier.Uncommon,
		description = "Triggers a loud alarm when tripped. Alerts defenders.",
		stackable = true,
		maxStack = 5,
		weight = 1,
	},
	noise_maker = {
		name = "Noise Maker",
		category = Cat.Trap,
		tier = Tier.Common,
		description = "Cans on string. Low-tech alarm system.",
		stackable = true,
		maxStack = 6,
		weight = 1,
	},

	------------------------------------------------------------------------
	-- Food Items
	------------------------------------------------------------------------
	-- Raw / Scavenged
	canned_beans = {
		name = "Canned Beans",
		category = Cat.Food,
		tier = Tier.Common,
		description = "Shelf-stable canned beans.",
		stackable = true,
		maxStack = 5,
		weight = 1,
		hungerRestore = 15,
		spoilDays = -1,
		canCookWith = true,
	},
	stale_bread = {
		name = "Stale Bread",
		category = Cat.Food,
		tier = Tier.Common,
		description = "Old but still edible bread.",
		stackable = true,
		maxStack = 5,
		weight = 1,
		hungerRestore = 10,
		spoilDays = 1,
	},
	crackers = {
		name = "Crackers",
		category = Cat.Food,
		tier = Tier.Common,
		description = "Dry crackers. Not filling but won't spoil fast.",
		stackable = true,
		maxStack = 8,
		weight = 1,
		hungerRestore = 8,
		spoilDays = -1,
	},
	bottled_water = {
		name = "Bottled Water",
		category = Cat.Food,
		tier = Tier.Common,
		description = "Clean drinking water.",
		stackable = true,
		maxStack = 5,
		weight = 1,
		hungerRestore = 5,
		spoilDays = -1,
	},
	raw_rabbit = {
		name = "Raw Rabbit",
		category = Cat.Food,
		tier = Tier.Common,
		description = "Fresh rabbit meat. Cook it first.",
		stackable = true,
		maxStack = 3,
		weight = 2,
		hungerRestore = 10,
		rawMeat = true,
		spoilDays = 1,
		canCookWith = true,
	},
	raw_venison = {
		name = "Raw Venison",
		category = Cat.Food,
		tier = Tier.Uncommon,
		description = "Large cut of deer meat. Excellent when cooked.",
		stackable = true,
		maxStack = 2,
		weight = 4,
		hungerRestore = 15,
		rawMeat = true,
		spoilDays = 1,
		canCookWith = true,
	},
	raw_fish = {
		name = "Raw Fish",
		category = Cat.Food,
		tier = Tier.Common,
		description = "Freshly caught fish. Best when cooked.",
		stackable = true,
		maxStack = 3,
		weight = 2,
		hungerRestore = 10,
		rawMeat = true,
		spoilDays = 1,
		canCookWith = true,
	},
	raw_bird = {
		name = "Raw Bird",
		category = Cat.Food,
		tier = Tier.Common,
		description = "Small game bird. Decent protein source.",
		stackable = true,
		maxStack = 3,
		weight = 1,
		hungerRestore = 8,
		rawMeat = true,
		spoilDays = 1,
		canCookWith = true,
	},
	vegetables = {
		name = "Fresh Vegetables",
		category = Cat.Food,
		tier = Tier.Uncommon,
		description = "Assorted fresh vegetables.",
		stackable = true,
		maxStack = 5,
		weight = 2,
		hungerRestore = 12,
		spoilDays = 2,
		canCookWith = true,
	},
	raw_meat = {
		name = "Raw Meat",
		category = Cat.Food,
		tier = Tier.Uncommon,
		description = "Uncooked beef or pork. Needs cooking.",
		stackable = true,
		maxStack = 3,
		weight = 3,
		hungerRestore = 12,
		rawMeat = true,
		spoilDays = 1,
		canCookWith = true,
	},
	spices = {
		name = "Spices",
		category = Cat.Food,
		tier = Tier.Uncommon,
		description = "Assorted cooking spices. Unlocks better recipes.",
		stackable = true,
		maxStack = 5,
		weight = 1,
		hungerRestore = 0,
		spoilDays = -1,
		canCookWith = true,
	},
	cooking_oil = {
		name = "Cooking Oil",
		category = Cat.Food,
		tier = Tier.Uncommon,
		description = "Vegetable oil for frying and cooking.",
		stackable = true,
		maxStack = 3,
		weight = 2,
		hungerRestore = 0,
		spoilDays = -1,
		canCookWith = true,
	},
	flour = {
		name = "Flour",
		category = Cat.Food,
		tier = Tier.Uncommon,
		description = "All-purpose flour for baking and breading.",
		stackable = true,
		maxStack = 4,
		weight = 2,
		hungerRestore = 0,
		spoilDays = -1,
		canCookWith = true,
	},
	steak = {
		name = "Premium Steak",
		category = Cat.Food,
		tier = Tier.Rare,
		description = "High-quality cut of beef. Luxury protein.",
		stackable = true,
		maxStack = 2,
		weight = 3,
		hungerRestore = 15,
		rawMeat = true,
		spoilDays = 1,
		canCookWith = true,
	},
	fresh_fish = {
		name = "Fresh Fish (Premium)",
		category = Cat.Food,
		tier = Tier.Rare,
		description = "Restaurant-quality fish fillet.",
		stackable = true,
		maxStack = 2,
		weight = 2,
		hungerRestore = 12,
		rawMeat = true,
		spoilDays = 1,
		canCookWith = true,
	},
	exotic_spices = {
		name = "Exotic Spices",
		category = Cat.Food,
		tier = Tier.Rare,
		description = "Rare imported spices. Unlocks the best recipes.",
		stackable = true,
		maxStack = 3,
		weight = 1,
		hungerRestore = 0,
		spoilDays = -1,
		canCookWith = true,
	},
	energy_drink = {
		name = "Energy Drink",
		category = Cat.Food,
		tier = Tier.Rare,
		description = "High-caffeine energy drink. Instant stamina boost.",
		stackable = true,
		maxStack = 3,
		weight = 1,
		hungerRestore = 10,
		spoilDays = -1,
		buff = { type = "SprintSpeed", amount = 1.3, duration = 120 },
	},
	mre = {
		name = "Survival MRE",
		category = Cat.Food,
		tier = Tier.Rare,
		description = "Military Meal Ready to Eat. Complete nutrition.",
		stackable = true,
		maxStack = 2,
		weight = 2,
		hungerRestore = 100,
		spoilDays = -1,
		buff = { type = "StaminaRestore", amount = 100, duration = 0 },
	},
	herbs = {
		name = "Herbs",
		category = Cat.Food,
		tier = Tier.Common,
		description = "Fresh herbs. Used in teas and cooking.",
		stackable = true,
		maxStack = 8,
		weight = 1,
		hungerRestore = 0,
		spoilDays = 2,
		canCookWith = true,
	},
	potato = {
		name = "Potato",
		category = Cat.Food,
		tier = Tier.Uncommon,
		description = "A hearty root vegetable.",
		stackable = true,
		maxStack = 6,
		weight = 1,
		hungerRestore = 8,
		spoilDays = 3,
		canCookWith = true,
	},
	carrot = {
		name = "Carrot",
		category = Cat.Food,
		tier = Tier.Uncommon,
		description = "Crunchy orange root. Good in stews.",
		stackable = true,
		maxStack = 6,
		weight = 1,
		hungerRestore = 6,
		spoilDays = 3,
		canCookWith = true,
	},

	-- Cooked food (created via cooking, not found as loot)
	heated_beans = {
		name = "Heated Beans",
		category = Cat.Food,
		tier = Tier.Common,
		description = "Warm canned beans. Simple comfort food.",
		stackable = true,
		maxStack = 5,
		weight = 1,
		hungerRestore = 20,
		spoilDays = 3,
		cooked = true,
	},
	roasted_rabbit = {
		name = "Roasted Rabbit",
		category = Cat.Food,
		tier = Tier.Uncommon,
		description = "Perfectly roasted rabbit. Hearty and filling.",
		stackable = true,
		maxStack = 3,
		weight = 2,
		hungerRestore = 30,
		spoilDays = 2,
		cooked = true,
		buff = { type = "StaminaRegen", amount = 1.5, duration = 120 },
	},
	venison_stew = {
		name = "Venison Stew",
		category = Cat.Food,
		tier = Tier.Rare,
		description = "Rich hearty stew with tender venison and vegetables.",
		stackable = true,
		maxStack = 2,
		weight = 3,
		hungerRestore = 80,
		spoilDays = 2,
		cooked = true,
		buff = { type = "DamageResistance", amount = 0.8, duration = 300 },
	},
	fish_tacos = {
		name = "Fish Tacos",
		category = Cat.Food,
		tier = Tier.Rare,
		description = "Crispy fish tacos with fresh seasoning.",
		stackable = true,
		maxStack = 3,
		weight = 2,
		hungerRestore = 60,
		spoilDays = 2,
		cooked = true,
		buff = { type = "SprintSpeed", amount = 1.15, duration = 180 },
	},
	herb_tea = {
		name = "Herb Tea",
		category = Cat.Food,
		tier = Tier.Common,
		description = "Warm herbal tea. Soothes the nerves.",
		stackable = true,
		maxStack = 5,
		weight = 1,
		hungerRestore = 15,
		spoilDays = 1,
		cooked = true,
		buff = { type = "SteadyAim", amount = 1, duration = 120 },
	},
	power_meal = {
		name = "Power Meal",
		category = Cat.Food,
		tier = Tier.Epic,
		description = "A masterfully cooked full meal. Peak performance.",
		stackable = true,
		maxStack = 1,
		weight = 3,
		hungerRestore = 100,
		spoilDays = 2,
		cooked = true,
		buff = { type = "AllStats", amount = 1.2, duration = 480 },
	},

	------------------------------------------------------------------------
	-- Fuel
	------------------------------------------------------------------------
	fuel_small = {
		name = "Fuel Can (Small)",
		category = Cat.Fuel,
		tier = Tier.Common,
		description = "Small jerry can of gasoline.",
		stackable = true,
		maxStack = 3,
		weight = 3,
		fuelAmount = 20,
	},
	fuel_medium = {
		name = "Fuel Can (Medium)",
		category = Cat.Fuel,
		tier = Tier.Uncommon,
		description = "Standard jerry can of gasoline.",
		stackable = true,
		maxStack = 2,
		weight = 5,
		fuelAmount = 45,
	},
	fuel_large = {
		name = "Fuel Drum",
		category = Cat.Fuel,
		tier = Tier.Rare,
		description = "Large fuel drum. Keeps the generator running.",
		stackable = false,
		maxStack = 1,
		weight = 10,
		fuelAmount = 80,
	},

	------------------------------------------------------------------------
	-- Generator Parts
	------------------------------------------------------------------------
	spark_plugs = {
		name = "Spark Plugs",
		category = Cat.GeneratorPart,
		tier = Tier.Uncommon,
		description = "Replacement spark plugs for the generator.",
		stackable = false,
		maxStack = 1,
		weight = 1,
		generatorUpgrade = 2,
	},
	wiring = {
		name = "Wiring",
		category = Cat.GeneratorPart,
		tier = Tier.Uncommon,
		description = "Electrical wiring to repair the generator.",
		stackable = false,
		maxStack = 1,
		weight = 2,
		generatorUpgrade = 2,
	},
	fan_belt = {
		name = "Fan Belt",
		category = Cat.GeneratorPart,
		tier = Tier.Uncommon,
		description = "Replacement fan belt for the generator motor.",
		stackable = false,
		maxStack = 1,
		weight = 1,
		generatorUpgrade = 2,
	},
	industrial_motor = {
		name = "Industrial Motor",
		category = Cat.GeneratorPart,
		tier = Tier.Rare,
		description = "Powerful industrial-grade motor.",
		stackable = false,
		maxStack = 1,
		weight = 8,
		generatorUpgrade = 3,
	},
	voltage_regulator = {
		name = "Voltage Regulator",
		category = Cat.GeneratorPart,
		tier = Tier.Rare,
		description = "Stabilizes power output for efficiency.",
		stackable = false,
		maxStack = 1,
		weight = 3,
		generatorUpgrade = 3,
	},
	heavy_fuel_tank = {
		name = "Heavy Fuel Tank",
		category = Cat.GeneratorPart,
		tier = Tier.Rare,
		description = "Large-capacity fuel tank upgrade.",
		stackable = false,
		maxStack = 1,
		weight = 6,
		generatorUpgrade = 3,
	},
	solar_panel = {
		name = "Solar Panel",
		category = Cat.GeneratorPart,
		tier = Tier.Epic,
		description = "Rooftop solar panel for passive charging.",
		stackable = false,
		maxStack = 1,
		weight = 8,
		generatorUpgrade = 4,
	},

	------------------------------------------------------------------------
	-- Weapons
	------------------------------------------------------------------------
	baseball_bat = {
		name = "Baseball Bat",
		category = Cat.Weapon,
		tier = Tier.Common,
		description = "Standard wooden bat. Reliable melee weapon.",
		stackable = false,
		maxStack = 1,
		weight = 3,
		weaponType = "Melee",
		damage = 18,
		swingSpeed = 0.7,
		range = 5,
	},
	crowbar = {
		name = "Crowbar",
		category = Cat.Weapon,
		tier = Tier.Common,
		description = "Heavy crowbar. Good for bashing and prying.",
		stackable = false,
		maxStack = 1,
		weight = 4,
		weaponType = "Melee",
		damage = 22,
		swingSpeed = 0.8,
		range = 5,
		canPryDoors = true,
	},
	kitchen_knife = {
		name = "Kitchen Knife",
		category = Cat.Weapon,
		tier = Tier.Common,
		description = "Sharp kitchen knife. Fast but short range.",
		stackable = false,
		maxStack = 1,
		weight = 1,
		weaponType = "Melee",
		damage = 14,
		swingSpeed = 0.4,
		range = 3,
	},
	fire_axe = {
		name = "Fire Axe",
		category = Cat.Weapon,
		tier = Tier.Uncommon,
		description = "Heavy fire axe. Devastating but slow.",
		stackable = false,
		maxStack = 1,
		weight = 5,
		weaponType = "Melee",
		damage = 35,
		swingSpeed = 1.0,
		range = 6,
		canBreakDoors = true,
	},
	pistol = {
		name = "Pistol",
		category = Cat.Weapon,
		tier = Tier.Uncommon,
		description = "9mm handgun. Effective at medium range.",
		stackable = false,
		maxStack = 1,
		weight = 2,
		weaponType = "Ranged",
		damage = 25,
		fireRate = 0.4,
		range = 60,
		ammoType = "pistol_ammo",
		magSize = 12,
	},
	shotgun = {
		name = "Shotgun",
		category = Cat.Weapon,
		tier = Tier.Rare,
		description = "Pump-action shotgun. Devastating at close range.",
		stackable = false,
		maxStack = 1,
		weight = 5,
		weaponType = "Ranged",
		damage = 45,
		fireRate = 1.0,
		range = 25,
		ammoType = "shotgun_shells",
		magSize = 6,
		spread = 15,
	},
	rifle = {
		name = "Hunting Rifle",
		category = Cat.Weapon,
		tier = Tier.Rare,
		description = "Bolt-action rifle. Long range and precise.",
		stackable = false,
		maxStack = 1,
		weight = 6,
		weaponType = "Ranged",
		damage = 60,
		fireRate = 1.5,
		range = 120,
		ammoType = "rifle_ammo",
		magSize = 5,
	},

	-- Ammo
	pistol_ammo = {
		name = "9mm Ammo",
		category = Cat.Ammo,
		tier = Tier.Uncommon,
		description = "Box of 9mm rounds.",
		stackable = true,
		maxStack = 60,
		weight = 1,
	},
	shotgun_shells = {
		name = "Shotgun Shells",
		category = Cat.Ammo,
		tier = Tier.Uncommon,
		description = "12-gauge shotgun shells.",
		stackable = true,
		maxStack = 30,
		weight = 1,
	},
	rifle_ammo = {
		name = "Rifle Ammo",
		category = Cat.Ammo,
		tier = Tier.Rare,
		description = "High-caliber rifle rounds.",
		stackable = true,
		maxStack = 20,
		weight = 1,
	},

	------------------------------------------------------------------------
	-- Tools
	------------------------------------------------------------------------
	lockpick = {
		name = "Lockpick Set",
		category = Cat.Tool,
		tier = Tier.Uncommon,
		description = "Picks locks without making noise. Limited uses.",
		stackable = true,
		maxStack = 5,
		weight = 1,
		uses = 3,
	},
	fishing_rod = {
		name = "Fishing Rod",
		category = Cat.Tool,
		tier = Tier.Common,
		description = "Crafted fishing rod for catching fish.",
		stackable = false,
		maxStack = 1,
		weight = 2,
	},
	snare_trap = {
		name = "Snare Trap",
		category = Cat.Tool,
		tier = Tier.Common,
		description = "Simple trap for catching small game.",
		stackable = true,
		maxStack = 4,
		weight = 2,
	},

	------------------------------------------------------------------------
	-- Light Sources
	------------------------------------------------------------------------
	flashlight = {
		name = "Flashlight",
		category = Cat.LightSource,
		tier = Tier.Common,
		description = "Battery-powered flashlight. Cone of light.",
		stackable = false,
		maxStack = 1,
		weight = 1,
		lightRadius = 30,
		duration = 300,
	},
	candle = {
		name = "Candle",
		category = Cat.LightSource,
		tier = Tier.Common,
		description = "Handmade candle. Small warm glow.",
		stackable = true,
		maxStack = 6,
		weight = 1,
		lightRadius = 10,
		duration = 180,
	},
	flare = {
		name = "Flare",
		category = Cat.LightSource,
		tier = Tier.Uncommon,
		description = "Bright emergency flare. Short duration.",
		stackable = true,
		maxStack = 4,
		weight = 1,
		lightRadius = 40,
		duration = 60,
	},
	glow_stick = {
		name = "Glow Stick",
		category = Cat.LightSource,
		tier = Tier.Rare,
		description = "Chemical glow stick. Crack and toss.",
		stackable = true,
		maxStack = 4,
		weight = 1,
		lightRadius = 15,
		duration = 300,
		throwable = true,
	},

	------------------------------------------------------------------------
	-- Seeds (for gardening)
	------------------------------------------------------------------------
	tomato_seed = {
		name = "Tomato Seeds",
		category = Cat.Seed,
		tier = Tier.Uncommon,
		description = "Plant these to grow tomatoes over time.",
		stackable = true,
		maxStack = 5,
		weight = 1,
		growthDays = 2,
		harvestItem = "vegetables",
	},
	potato_seed = {
		name = "Potato Seeds",
		category = Cat.Seed,
		tier = Tier.Uncommon,
		description = "Plant these to grow potatoes over time.",
		stackable = true,
		maxStack = 5,
		weight = 1,
		growthDays = 2,
		harvestItem = "potato",
	},
	herb_seed = {
		name = "Herb Seeds",
		category = Cat.Seed,
		tier = Tier.Common,
		description = "Plant these to grow useful herbs.",
		stackable = true,
		maxStack = 5,
		weight = 1,
		growthDays = 1,
		harvestItem = "herbs",
	},

	------------------------------------------------------------------------
	-- Cooking Stations (as buildable items)
	------------------------------------------------------------------------
	campfire_kit = {
		name = "Campfire Kit",
		category = Cat.CookingStation,
		tier = Tier.Common,
		description = "Scrap wood and kindling. Build a campfire.",
		stackable = false,
		maxStack = 1,
		weight = 4,
		stationType = "Campfire",
	},
	stove_parts = {
		name = "Stove Parts",
		category = Cat.CookingStation,
		tier = Tier.Uncommon,
		description = "Gas canister, metal grate, and igniter.",
		stackable = false,
		maxStack = 1,
		weight = 6,
		stationType = "Stove",
	},
	kitchen_parts = {
		name = "Kitchen Restoration Parts",
		category = Cat.CookingStation,
		tier = Tier.Rare,
		description = "Working oven, clean water supply, and countertops.",
		stackable = false,
		maxStack = 1,
		weight = 12,
		stationType = "FullKitchen",
	},

	------------------------------------------------------------------------
	-- Backpacks (upgrade inventory capacity)
	------------------------------------------------------------------------
	small_backpack = {
		name = "Small Backpack",
		category = Cat.Backpack,
		tier = Tier.Uncommon,
		description = "A durable school backpack. Holds 10 items.",
		stackable = false,
		maxStack = 1,
		weight = 2,
		backpackSlots = 10,
	},
	medium_backpack = {
		name = "Hiking Backpack",
		category = Cat.Backpack,
		tier = Tier.Rare,
		description = "Sturdy hiking backpack with multiple compartments. Holds 15 items.",
		stackable = false,
		maxStack = 1,
		weight = 3,
		backpackSlots = 15,
	},
	large_backpack = {
		name = "Military Rucksack",
		category = Cat.Backpack,
		tier = Tier.Epic,
		description = "Heavy-duty military rucksack. Holds 20 items.",
		stackable = false,
		maxStack = 1,
		weight = 4,
		backpackSlots = 20,
	},

	------------------------------------------------------------------------
	-- Recipe Cards
	------------------------------------------------------------------------
	recipe_heated_beans = {
		name = "Recipe: Heated Beans",
		category = Cat.Recipe,
		tier = Tier.Common,
		description = "A simple recipe card for heated beans.",
		stackable = false,
		maxStack = 1,
		weight = 0,
		recipeId = "heated_beans",
	},
	recipe_roasted_rabbit = {
		name = "Recipe: Roasted Rabbit",
		category = Cat.Recipe,
		tier = Tier.Common,
		description = "Recipe for campfire-roasted rabbit.",
		stackable = false,
		maxStack = 1,
		weight = 0,
		recipeId = "roasted_rabbit",
	},
	recipe_venison_stew = {
		name = "Recipe: Venison Stew",
		category = Cat.Recipe,
		tier = Tier.Uncommon,
		description = "Recipe for rich venison stew.",
		stackable = false,
		maxStack = 1,
		weight = 0,
		recipeId = "venison_stew",
	},
	recipe_fish_tacos = {
		name = "Recipe: Fish Tacos",
		category = Cat.Recipe,
		tier = Tier.Uncommon,
		description = "Recipe for crispy fish tacos.",
		stackable = false,
		maxStack = 1,
		weight = 0,
		recipeId = "fish_tacos",
	},
	recipe_herb_tea = {
		name = "Recipe: Herb Tea",
		category = Cat.Recipe,
		tier = Tier.Common,
		description = "Recipe for soothing herbal tea.",
		stackable = false,
		maxStack = 1,
		weight = 0,
		recipeId = "herb_tea",
	},
	recipe_power_meal = {
		name = "Recipe: Power Meal",
		category = Cat.Recipe,
		tier = Tier.Rare,
		description = "The ultimate performance meal recipe.",
		stackable = false,
		maxStack = 1,
		weight = 0,
		recipeId = "power_meal",
	},
}

------------------------------------------------------------------------
-- Loot tables by zone
------------------------------------------------------------------------
ItemDatabase.ZoneLoot = {
	[1] = {
		"plywood", "duct_tape", "wooden_planks", "nails", "scrap_metal",
		"canned_beans", "stale_bread", "crackers", "bottled_water",
		"fuel_small", "noise_maker", "flashlight", "candle",
		"kitchen_knife", "herbs", "recipe_heated_beans", "recipe_herb_tea",
		"herb_seed", "campfire_kit",
	},
	[2] = {
		"reinforced_boards", "steel_nails", "chain_lock", "sandbags",
		"vegetables", "raw_meat", "spices", "cooking_oil", "flour",
		"potato", "carrot", "fuel_medium",
		"spike_strip", "tripwire", "flare",
		"crowbar", "fire_axe", "pistol", "pistol_ammo",
		"lockpick", "snare_trap",
		"spark_plugs", "wiring", "fan_belt",
		"stove_parts", "recipe_roasted_rabbit", "recipe_fish_tacos",
		"tomato_seed", "potato_seed",
		"small_backpack",
	},
	[3] = {
		"steel_panels", "bulletproof_glass", "industrial_lock", "steel_door",
		"turret_components", "electric_fence_kit",
		"steak", "fresh_fish", "exotic_spices", "energy_drink", "mre",
		"fuel_large",
		"shotgun", "rifle", "shotgun_shells", "rifle_ammo",
		"glow_stick",
		"industrial_motor", "voltage_regulator", "heavy_fuel_tank", "solar_panel",
		"kitchen_parts", "recipe_venison_stew", "recipe_power_meal",
		"medium_backpack", "large_backpack",
	},
}

-- Bonus location loot overrides
ItemDatabase.BonusLoot = {
	HardwareStore = {
		"plywood", "wooden_planks", "nails", "scrap_metal",
		"reinforced_boards", "steel_nails", "chain_lock", "sandbags",
		"steel_panels", "industrial_lock",
		"crowbar", "fire_axe", "duct_tape",
		"spike_strip", "tripwire", "noise_maker",
	},
	PoliceStation = {
		"pistol", "shotgun", "rifle",
		"pistol_ammo", "pistol_ammo", "shotgun_shells", "rifle_ammo",
		"flashlight", "flare", "glow_stick",
		"bulletproof_glass", "steel_panels",
		"lockpick",
	},
	GasStation = {
		"fuel_small", "fuel_medium", "fuel_large",
		"fuel_small", "fuel_medium",
		"crackers", "energy_drink", "bottled_water",
		"flashlight", "candle",
	},
	AbandonedSchool = {
		"plywood", "wooden_planks", "scrap_metal",
		"canned_beans", "crackers", "bottled_water",
		"stale_bread", "candle", "flashlight",
		"baseball_bat", "crowbar",
		"duct_tape", "nails",
		"recipe_heated_beans",
	},
	UndergroundBunker = {
		"steel_panels", "bulletproof_glass", "industrial_lock", "steel_door",
		"turret_components", "electric_fence_kit",
		"mre", "mre", "energy_drink",
		"rifle", "shotgun", "rifle_ammo", "shotgun_shells",
		"industrial_motor", "voltage_regulator", "heavy_fuel_tank", "solar_panel",
		"fuel_large", "fuel_large",
		"recipe_power_meal",
	},
}

-- Helper: get item data by ID
function ItemDatabase.GetItem(itemId: string)
	return ItemDatabase.Items[itemId]
end

-- Helper: get random loot for a zone
function ItemDatabase.GetRandomLootForZone(zone: number, count: number): { string }
	local pool = ItemDatabase.ZoneLoot[zone]
	if not pool then return {} end

	local result = {}
	for _ = 1, count do
		local idx = math.random(1, #pool)
		table.insert(result, pool[idx])
	end
	return result
end

return ItemDatabase
